name: excel_parser
description: A excel parser tools.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  path: any
  args: ^2.2.0
  excel: any
  tuple: any

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
